GET http://localhost:8080/api/products/1
Accept: application/json

###
GET http://localhost:8080/api/products/
Accept: application/json

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "담보채권",
  "price": 100000000
}

###

